// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class Information : UIViewController
	{
		public Information (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			if(MainViewController.hasJustUnlockedAchievement){
				this.badgeNotification.SetImage (UIImage.FromFile ("BadgesNotifications.png"),UIControlState.Normal);
			}
			else{
				this.badgeNotification.SetImage(UIImage.FromFile("BadgesOff.png"), UIControlState.Normal);
			}
		}

		public override void ViewDidLoad () {
			base.ViewDidLoad ();

			scrollView.Scrolled += (sender, e) => {
				float offset = scrollView.ContentOffset.X;
				float pagesize = scrollView.Frame.Size.Width;
				int page = (int)Math.Floor((offset + (pagesize/2))/pagesize);
				scroller.CurrentPage = page;
			};
		}
		partial void toInfo (NSObject sender)
		{
			MainNavigationController.goInfo = true;
			DismissViewController(false,null);
		}
		partial void toStats (NSObject sender)
		{
			MainNavigationController.goStats = true;
			DismissViewController(false,null);
		}
		partial void toTrip (NSObject sender)
		{
			MainNavigationController.goTrip = true;
			DismissViewController(false,null);
		}
		partial void toTrophies (NSObject sender)
		{
			MainNavigationController.goTrophies = true;
			DismissViewController(false,null);
		}

	}
}
