// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class MainNavigationController : UIViewController
	{

		public static bool goTrip = true;
		public static bool goStats = false;
		public static bool goTrophies = false;
		public static bool goInfo = false;

		public MainNavigationController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear(bool animated){
			base.ViewWillAppear (animated);


		}

		public override void ViewDidLoad(){
			base.ViewDidLoad ();

		}

		public override void ViewDidAppear(bool animated){
			base.ViewDidAppear (animated);

			if (goTrip) {
				goTrip = false;
				this.PerformSegue ("toTripID", this);
			} else if (goTrophies) {
				goTrophies = false;
				this.PerformSegue ("toTrophiesID", this);
			} else if (goInfo) {
				goInfo = false;
				this.PerformSegue ("toInfoID", this);
			} else if (goStats) {
				goStats = false;
				this.PerformSegue ("toStatsID", this);
			}
		}

	}
}