// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.AudioToolbox;

namespace FrameWorkApp
{
	public partial class MenuScreenTiles : UIViewController
	{
		private SystemSound sound;

		public MenuScreenTiles (IntPtr handle) : base (handle)
		{
		}

		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations ()
		{
			return UIInterfaceOrientationMask.Portrait;
		}
		public override UIInterfaceOrientation PreferredInterfaceOrientationForPresentation ()
		{
			return UIInterfaceOrientation.Portrait;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

		}


		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);


		}
		partial void menuToHome (NSObject sender)
		{
			DismissViewController(true,null);
		}

		partial void achievementsSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}
		}

		partial void questionSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/Water.aiff");

				sound.PlaySystemSound ();
			}

		}

		partial void settingSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}

		}
		partial void shareSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}

		}
		partial void statsSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}

		}
		partial void takeTripSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}

		}
		partial void tripLogSound (NSObject sender)
		{
			if (MainViewController.isAudioOn) {
				//enable audio
				AudioSession.Initialize ();


				//load the sound
				sound = SystemSound.FromFile ("Sounds/KeyboardClick.aiff");

				sound.PlaySystemSound ();
			}

		}
	}
}
