// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class SettingsScreen : UIViewController
	{


		public SettingsScreen (IntPtr handle) : base (handle)
		{

		}

		public override void ViewWillAppear(bool animated){
			base.ViewWillAppear (animated);
			if (MainViewController.isAudioOn) {
				isAudioEnabled.SetState (true, true);
			} else {
				isAudioEnabled.SetState (false, true);
			}

		}
		public override void ViewDidLoad(){
			base.ViewDidLoad ();



		}
		public override void ViewWillDisappear(bool animated){
			base.ViewWillDisappear (animated);

			if (isAudioEnabled.On) {
				MainViewController.isAudioOn = true;
			} else {
				MainViewController.isAudioOn = false;
			}
		}
		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations ()
		{
			return UIInterfaceOrientationMask.Portrait;
		}
	
	}
}
