// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class TripLogDetailScreen : UIViewController
	{
		public static Trip currentTrip {get;set;}

		public TripLogDetailScreen (IntPtr handle) : base (handle)
		{
		}

		public TripLogScreen Delegate {get;set;} // will be used to Save, Delete later
		public void SetTask (TripLogScreen d, Trip trip) {
			Delegate = d;
			currentTrip = trip;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			tripDistanceLabel.Text = currentTrip.Distance.ToString("0.0");
			hardStartsLabel.Text = currentTrip.HardStarts.ToString();
			hardStopsLabel.Text = currentTrip.HardBrakes.ToString();
			hardTurnsLabel.Text = currentTrip.HardTurns.ToString();
			pointsEarned.Text = currentTrip.Points ().ToString ();


			if(MainViewController.hasJustUnlockedAchievement){
				this.badgeNotification.SetImage (UIImage.FromFile ("BadgesNotifications.png"),UIControlState.Normal);
			}
			else{
				this.badgeNotification.SetImage(UIImage.FromFile("BadgesOff.png"), UIControlState.Normal);
			}



		}

		partial void toInfo (NSObject sender)
		{
			MainNavigationController.goInfo = true;
			DismissViewController(false,null);
		}
		partial void toStats (NSObject sender)
		{
			MainNavigationController.goStats = true;
			DismissViewController(false,null);
		}
		partial void toTrip (NSObject sender)
		{
			MainNavigationController.goTrip = true;
			DismissViewController(false,null);
		}
		partial void toTrophies (NSObject sender)
		{
			MainNavigationController.goTrophies = true;
			DismissViewController(false,null);
		}
	}
}
